<a href="https://colab.research.google.com/github/gold999-lgtm/Project1/blob/main/Pokomon_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [64]:
import os
print(os.getcwd())

/content


In [65]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Flatten,Dense

In [103]:
classifier=Sequential()
classifier.add(Conv2D(32,(3,3),input_shape=(64,64,3),activation="relu"))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Conv2D(32,(3,3),activation="relu"))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Flatten())
classifier.add(Dense(units=128,activation="relu"))
classifier.add(Dense(units=3,activation="softmax"))
classifier.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [104]:
from keras.preprocessing.image import ImageDataGenerator
train_datagen=ImageDataGenerator(rescale=1./255,
                                 shear_range=0.2,
                                 zoom_range=0.2,
                                 horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1.0/255)
training_set=train_datagen.flow_from_directory("/content/drive/My Drive/dataset/training_set",
                                               target_size=(64,64),
                                               batch_size=32,
                                               class_mode="categorical")
test_set=test_datagen.flow_from_directory("/content/drive/My Drive/dataset/test_set",
                                               target_size=(64,64),
                                               batch_size=32,
                                               class_mode="categorical")

Found 445 images belonging to 3 classes.
Found 238 images belonging to 3 classes.


In [105]:
print(type(training_set))
print(type(train_datagen))

<class 'keras.preprocessing.image.DirectoryIterator'>
<class 'keras.preprocessing.image.ImageDataGenerator'>


In [106]:
history=classifier.fit_generator(training_set,
                         steps_per_epoch=100,
                         epochs=5,
                         validation_data=test_set,
                         validation_steps=200)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  """


Epoch 1/5
 10/100 [==>...........................] - ETA: 1:53 - loss: 1.0009 - accuracy: 0.5156

/usr/local/lib/python3.7/dist-packages/PIL/Image.py:960: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


100/100 [==============================] - 28s 267ms/step - loss: 0.8787 - accuracy: 0.5978 - val_loss: 0.6085 - val_accuracy: 0.8151


In [107]:
import numpy as np
from keras.preprocessing import image
test_image=image.load_img("/content/drive/My Drive/balbasaur.png",target_size=(64,64))
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)
predictions=classifier.predict(test_image)
print(training_set.class_indices)
print((predictions>0.5).astype("int32"))

{'bulbasaur': 0, 'charmander': 1, 'pikachu': 2}
[[1 0 0]]


In [108]:
import keras
from keras.applications.vgg16 import VGG16


In [109]:
conv_base=VGG16(weights="imagenet",include_top=False,input_shape=(150,150,3))

In [110]:
conv_base.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 150, 150, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 150, 150, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 150, 150, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 75, 75, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 75, 75, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 75, 75, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 37, 37, 128)       0     

In [111]:
from keras import models
from keras import layers
import os
model=models.Sequential()
model.add(conv_base)
model.add(layers.Flatten())
model.add(layers.Dense(256,activation="relu"))
model.add(layers.Dense(3,activation="softmax"))

In [112]:
conv_base.trainable=False
conv_base.summary()
model.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 150, 150, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 150, 150, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 150, 150, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 75, 75, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 75, 75, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 75, 75, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 37, 37, 128)       0     

In [113]:
base_dir="/content/drive/My Drive/dataset/"
train_dir=os.path.join(base_dir,"training_set")
test_dir=os.path.join(base_dir,"test_set")

In [114]:
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
train_datagen=ImageDataGenerator(rescale=1./255,
                                 rotation_range=40,
                                 width_shift_range=0.2,
                                 height_shift_range=0.2,
                                 shear_range=0.2,
                                 zoom_range=0.2,
                                 horizontal_flip=True,
                                 fill_mode="nearest")
test_datagen=ImageDataGenerator(rescale=1./255)
train_generator=train_datagen.flow_from_directory(test_dir,
                                                  target_size=(150,150),
                                                  batch_size=20,
                                                  class_mode="categorical")
test_generator=test_datagen.flow_from_directory(test_dir,
                                                target_size=(150,150),
                                                batch_size=20,
                                                class_mode="categorical")

Found 238 images belonging to 3 classes.
Found 238 images belonging to 3 classes.


In [115]:
model.compile(loss="categorical_crossentropy",
              optimizer="rmsprop",
              metrics=["acc"])
history=model.fit_generator(train_generator,
                            steps_per_epoch=100,
                            epochs=30,
                            validation_data=test_generator,
                            validation_steps=50)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  


Epoch 1/30
100/100 [==============================] - 146s 1s/step - loss: 3.1072 - acc: 0.4790 - val_loss: 2.2925 - val_acc: 0.3445


In [116]:
import numpy as np
from keras.preprocessing import image
test_image=image.load_img("/content/drive/My Drive/balbasaur.png",target_size=(64,64))
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)
predictions=classifier.predict(test_image)
print(training_set.class_indices)
print((predictions>0.5).astype("int32"))

{'bulbasaur': 0, 'charmander': 1, 'pikachu': 2}
[[1 0 0]]


In [117]:
conv_base.trainable=True
set_trainable=False
for layer in conv_base.layers:
  if layer.name=="block5_conv1":
    set_trainable=True
  if set_trainable:
    layer.trainable=True
  else:
    layer.trainable=False
model.compile(loss="categorical_crossentropy",
              optimizer="rmsprop",
              metrics=["acc"])
history=model.fit_generator(train_generator,
                            steps_per_epoch=100,
                            epochs=30,
                            validation_data=test_generator,
                            validation_steps=50)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.


Epoch 1/30
100/100 [==============================] - 158s 2s/step - loss: 73.3070 - acc: 0.3529 - val_loss: 1.0958 - val_acc: 0.3739


In [119]:
import numpy as np
from keras.preprocessing import image
test_image=image.load_img("/content/drive/My Drive/balbasaur.png",target_size=(150,150))
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)
predictions=model.predict(test_image)
print(training_set.class_indices)
print((predictions>0.5).astype("int32"))

{'bulbasaur': 0, 'charmander': 1, 'pikachu': 2}
[[1 0 0]]
